variable "table_name" {}
variable "attribute" {}
variable "read_capacity" {}
variable "write_capacity" {}
variable "hash_key" {}
variable "range_key" {}
variable "encryption" {}
variable "encryption_kms_key_arn_cmk" {}
variable "billing_mode" {}
variable "stream_enabled" {}
variable "stream_view_type" {}
variable "point_in_time_recovery" {}
variable "ttl_enabled" {}
variable "ttl_attribute_name" {}
variable "application_id" {}
variable "default_tags" {}
